name: ogg_opus_player
description: An ogg opus file player and recorder for flutter.
version: 0.7.0
homepage: https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/ogg_opus_player

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.4
  system_clock: ^3.0.0

dev_dependencies:
  ffigen: ^20.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      ios:
        pluginClass: OggOpusPlayerPlugin
      macos:
        pluginClass: OggOpusPlayerPlugin
      android:
        package: one.mixin.oggOpusPlayer
        pluginClass: OggOpusPlayerPlugin
